name: Build V2RAY serf APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x ./V2rayNG/gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease -x lint
      working-directory: ./V2rayNG

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: V2RAY-serf-release
        path: V2rayNG/app/build/outputs/apk/release/*.apk
